### ISSUE TITLE
BugOverload. Страница фильма. Кнопка трейлера открывает iframe на покупку билета, а не на видео трейлера

### ISSUE THREAD

**Issue by Ivan-Bir** [VK-BMSTU-QA/homework-2-spring-2023#1]
**Приоритет**: средний
**URL**: https://movie-gate.online/film/1
**Окружение**: ОС Linux version 6.1.11-arch1-1, Браузер Google chrome, версия 109.0.5414.74 (Официальная сборка) (64 бит), масштаб 100%, разрешение 1920х1080

**Шаги воспроизведения**:
1. Перейти по url https://movie-gate.online/film/1
2. Нажать на кнопку "Трейлер"

**Фактический результат**: Открывает модальное окно с iframe afisha.yandex.ru
**Ожидаемый результат**: Открывает модальное окно со встроенным в iframe youtube видео

**Артефакты**:
* Скриншот
![image](https://user-images.githubusercontent.com/91963263/223377035-dcfbd7c9-03e8-42d4-984e-6fe54f7cc6f8.png)

**Comment by lonkidely** [comment]
> **Фактический результат**: Открывает модальное окно со встроенным в iframe youtube видео
> **Ожидаемый результат**: Открывает модальное окно с iframe afisha.yandex.ru

Наоборот

**Comment by Ivan-Bir** [comment]
Исправил

**Comment by Andeo1812** [comment]
Апрув

**Comment by Mike5535** [comment]
Аппрув

**Comment by lonkidely** [comment]
аппрув

**Comment by Ivan-Bir** [comment]
upd

**Comment by Andeo1812** [comment]
аппрув

**Comment by Mike5535** [comment]
Аппрув

**Comment by lonkidely** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
аппрув
