### ISSUE TITLE
VDonate. Редактирование профиля пользователя. Неверное ограничение максимальной длины email.

### ISSUE THREAD

**Issue by george007361** [VK-BMSTU-QA/homework-2-spring-2023#10]
> **Приоритет:** minor
> **URL:** https://vdonate.ml/profile?id=<ВАШ ID>
> **Окружение:** ОС Linux Ubuntu 22.04 5.19.0-35-generic, Браузер Google Chrome, Version 110.0.5481.96 (Official Build) (64-bit), масштаб 150%, разрешение 1920х1080

**Шаги воспроизведения:**
1. Нажать на значок карандаша (редактирование профиля)
2. В появившемся оверлее ввести email длиной 65-255 символов
3. Нажать на кнопку "Изменить"

**Фактический результат:**  Невозможность установить почту длиннее 64 символов 
**Ожидаемый результат:**  Возможность установить email длиной до 255 символов

**Артефакты:**
![image](https://user-images.githubusercontent.com/92120286/224563602-6da65e70-aebe-4d63-bdf1-5971455eced8.png)

**Comment by zeronethunter** [comment]
Аппрув
