### ISSUE TITLE
Base. Главная страница. Нарушается плавность рендринга карусели

### ISSUE THREAD

**Issue by tUnknownLegend** [VK-BMSTU-QA/homework-2-spring-2023#18]
**Приоритет:** minor
**Окружение:** Ubuntu, Chrome 109.0.5414.119
**Описание:** Нарушается плавность рендринга карусели. Создает ощущение медленной работы сайта у пользователя

**URL:** [https://www.reazon.ru/](https://www.reazon.ru/)
**Как воспроизвести:**
1. зайти на главную страницу
2. обратить внимание на загруку страницы, в частности на загрузку карусели товаров

**Ожидаемый результат**: загружаются карточки со спиннером, затем они заполняются информацией
**Фактический результат:** нарушается плавность рендеринга. Вначале рендерится страница, затем карточки товаров
**[Скринкаст](https://cloud.mail.ru/public/1h1k/ACoaCaH82)**

**Comment by thelvv** [comment]
мне кажется, это minor, тк логика не нарушена

**Comment by tUnknownLegend** [comment]
> мне кажется, это minor, тк логика не нарушена

исправил

**Comment by thelvv** [comment]
approve

**Comment by EuphoriaAbsorber** [comment]
аппрув

**Comment by tUnknownLegend** [comment]
Все же скорее не баг, а предложение для улучшения
