### ISSUE TITLE
BugOverload. Страница фильма. Неверное отображение числа в поле "Бюджет"

### ISSUE THREAD

**Issue by Ivan-Bir** [VK-BMSTU-QA/homework-2-spring-2023#3]
**Приоритет**: низкий
**URL**: https://movie-gate.online/film/1
**Окружение**: ОС Linux version 6.1.11-arch1-1, Браузер Google chrome, версия 109.0.5414.74 (Официальная сборка) (64 бит), масштаб 100%, разрешение 1920х1080

**Шаги воспроизведения**:
1. Перейти на страницу фильма https://movie-gate.online/film/1
2. Открыть "Подробности"
3. Проверить поле "Бюджет"

**Фактический результат**: Отображается "$ 06 000 000"
**Ожидаемый результат**: Должно отображаться "$ 6 000 000"
**Артефакты**:
* Скриншот
![image](https://user-images.githubusercontent.com/91963263/223383023-ce44dbd6-b800-40b7-ab72-a4335269815a.png)

**Comment by lonkidely** [comment]
> **Фактический результат**: Должно отображаться "$ 6 000 000"
> **Ожидаемый результат**: Отображается "$ 06 000 000"

И тут наоборот

**Comment by Ivan-Bir** [comment]
Исправил

**Comment by Andeo1812** [comment]
Апрув

**Comment by Mike5535** [comment]
Аппрув

**Comment by lonkidely** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
аппрув
