### ISSUE TITLE
Base. Страница корзины. Не сохраняется дата доставки при обновлении страницы или переходе на другую страницу.

### ISSUE THREAD

**Issue by Liza1040** [VK-BMSTU-QA/homework-2-spring-2023#34]
**Приоритет:** major
**Окружение:** Ubuntu, Chrome 110.0.5481.96
**Описание:** при обновлении страницы или переходе на другую страницу ранее выбранная дата доставки не сохраняется. Это неудобно для пользователя, т.к. ему нужно заново выбрать дату. Либо он может этого не заметить и сделать заказ с неправильной датой.

**URL:** https://www.reazon.ru/cart
**Шаги воспроизведения:**

1. Добавить товар в корзину
2. Зайти на страницу корзины
3. Кликнуть на раскрывающийся список дат доставки
4. Выбрать любой вариант, кроме первого
5. Обновить страницу

**Фактический результат:** при обновлении страницы или переходе на другую страницу выбранная дата доставки не сохраняется и меняется на дату, которая стоит первая в раскрывающемся списке.
**Ожидаемый результат:** выбранная дата доставки сохраняется и не меняется при обновлении или переходе на другую страницу
**Скриншот:** 
![Раскрывающийся список даты доставки](https://user-images.githubusercontent.com/95960035/224741363-a651dec5-8ac1-4002-be63-35d62a3c24fa.png)

**Comment by tUnknownLegend** [comment]
approve, уровни приоритета еще отдельно обсудим как будем называть :)

**Comment by thelvv** [comment]
approve

**Comment by thelvv** [comment]
approve

**Comment by EuphoriaAbsorber** [comment]
аппрув
