### ISSUE TITLE
BugOverload. Страница фильма. В поле информации об общем числе актеров выводится 0

### ISSUE THREAD

**Issue by Ivan-Bir** [VK-BMSTU-QA/homework-2-spring-2023#4]
**Приоритет**: низкий
**URL**: https://movie-gate.online/film/1/
**Окружение**: ОС Linux version 6.1.11-arch1-1, Браузер Google chrome, версия 109.0.5414.74 (Официальная сборка) (64 бит), масштаб 100%, разрешение 1920х1080

**Шаги воспроизведения**:
1. Перейти на страницу фильма https://movie-gate.online/film/1
2. Открыть "Подробности"
3. Проверить блок "В главных ролях"

**Фактический результат**: "Всего: 0 актёров"
**Ожидаемый результат**: "Всего: 2 актёра"

**Артефакты**:
* Скриншот
![image](https://user-images.githubusercontent.com/91963263/223384053-cf6f7f00-c336-4250-931a-955988a801b3.png)

**Comment by lonkidely** [comment]
апрув

**Comment by Andeo1812** [comment]
Апрув

**Comment by Mike5535** [comment]
Аппрув

**Comment by alexey-ershkov** [comment]
аппрув
