### ISSUE TITLE
VDonate. Лайк к посту. Избыточное появление лоадера при нажатии на лайк

### ISSUE THREAD

**Issue by themilchenko** [VK-BMSTU-QA/homework-2-spring-2023#40]
`Приоритет:` Major
`URL:` https://vdonate.ml/profile?id=6
`Окружение:` Firefox Version 110.0.1 (64-bit)

#### Как воспроизвести:

1. Авторизироваться;
2. Найти любой пост (например, в ленте);
3. Навести курсор на кнопку лайка;
4. Нажать на кнопку.

`Ожидаемый результат`: Содержимое компонента должно мгновенно инкрементироваться, а цвет меняться на фиолетовый.

`Фактический результат`: Перед изменением содержимого компонента появляется лоадер.

#### Артефакты

![like_loader](https://user-images.githubusercontent.com/70635146/224858255-84536158-a446-4f78-8f18-cca41ec9f3a0.jpg)

**Comment by george007361** [comment]
Аппрув

**Comment by zeronethunter** [comment]
Приоритет я бы повыше сделал (хотя бы minor), всё же это главный контент сервиса, нужно, чтобы работало идеально

**Comment by MrLeonardPak** [comment]
Поправь заголовок

**Comment by MrLeonardPak** [comment]
Аппрув

**Comment by zeronethunter** [comment]
Аппрув

**Comment by mistergahan** [comment]
Избыточное Появление лоадера при нажатии на лайк

**Comment by mistergahan** [comment]
теперь Аппрув
