### ISSUE TITLE
Base. Страница пользователя. Отсутствует валидация/предложения для автозаполнения полей карточки адреса

### ISSUE THREAD

**Issue by thelvv** [VK-BMSTU-QA/homework-2-spring-2023#46]
__Приоритет__: major

__URL:__ https://www.reazon.ru/user (необходима авторизация)
__Как воспроизвести:__

1. авторизоваться
2. нажать на кнопку добавления новой карточки адреса
3. заполнить все поля
4. нажать кнопку "Применить"

__Ожидаемый результат:__ появляется сообщение, говорящее о неправильности введенного адреса
__Альтернативный ожидаемый результат:__ во время заполнения полей адреса появляется выпадающее меню с предложениями автозаполнения 
__Фактический результат:__ нет предложений для автозаполнения и валидации полей

**Comment by tUnknownLegend** [comment]
Лучше описать однозначно ожидаемы результат. Но поскольку такой логики вообще не закладывалось, то это не баг, а enhensment

**Comment by tUnknownLegend** [comment]
approve

**Comment by Liza1040** [comment]
approve

**Comment by Liza1040** [comment]
approve

**Comment by EuphoriaAbsorber** [comment]
аппрув

**Comment by tUnknownLegend** [comment]
работает как ождается, поэтому закрываем issue
