### ISSUE TITLE
VDonate. Комментарий к посту. Избыточное появление лоадера при нажатии на кнопку комментария

### ISSUE THREAD

**Issue by themilchenko** [VK-BMSTU-QA/homework-2-spring-2023#47]
`Приоритет:` Major
`URL:` https://vdonate.ml/profile?id=6
`Окружение:` Firefox Version 110.0.1 (64-bit)

#### Как воспроизвести:

1. Авторизироваться;
2. Найти любой пост (например, в ленте);
3. Навести курсор на кнопку комментрия;
4. Нажать на кнопку.

`Ожидаемый результат`: Появление комментариев не должно сопровождаться фиктивным лоадером.
`Фактический результат`: Перед появлением комментариев появляется лоадер.

#### Артефакты

![comment_loader](https://user-images.githubusercontent.com/70635146/224858332-164f5ca5-4444-4960-ac99-f700af84f9bf.jpg)

**Comment by MrLeonardPak** [comment]
Аппрув

**Comment by zeronethunter** [comment]
Аппрув

**Comment by mistergahan** [comment]
Избыточное/ неуместное появление лоадера при нажатии на кнопку комментария

**Comment by mistergahan** [comment]
теперь Аппрув
