### ISSUE TITLE
VDonate. Прыгающая верстка. Появление комментариев смещает текующий пост вверх

### ISSUE THREAD

**Issue by themilchenko** [VK-BMSTU-QA/homework-2-spring-2023#49]
`Приоритет:` Minor
`URL:` https://vdonate.ml/feed
`Окружение:`  Microsoft Edge Version 110.0.1587.69 (64-bit)

#### Как воспроизвести:

1. Авторизироваться;
2. Найти пост, находящийся вторым или дальше;
3. Навести курсор на кнопку комментрия;
4. Нажать на кнопку.

`Ожидаемый результат`: Статичное появление комментариев.
`Фактический результат`:     Верстка страницы "съезжает" при появлении всех комментариев.

#### Артефакты

![photo_2023-03-14_00-25-29](https://user-images.githubusercontent.com/70635146/224849118-06f5cc4c-ec8c-4b5e-8c6d-ea7d44bfe6db.jpg)

![photo_2023-03-14_00-25-31](https://user-images.githubusercontent.com/70635146/224849116-9962f1a1-e27f-4670-846f-ecfaf4993db5.jpg)

**Comment by MrLeonardPak** [comment]
Аппурв

**Comment by zeronethunter** [comment]
Аппрув

**Comment by george007361** [comment]
Аппрув

**Comment by mistergahan** [comment]
Аппрув
