### ISSUE TITLE
BugOverload. Страница авторизации/регистрации. Отпускание курсора вне модального окна закрывает его

### ISSUE THREAD

**Issue by Ivan-Bir** [VK-BMSTU-QA/homework-2-spring-2023#5]
**Приоритет**: средний
**URL**: https://movie-gate.online/login/ или https://movie-gate.online/signup/
**Окружение**: ОС Linux version 6.1.11-arch1-1, Браузер Google chrome, версия 109.0.5414.74 (Официальная сборка) (64 бит), масштаб 100%, разрешение 1920х1080

**Шаги воспроизведения**:
1. Открыть модальное окно регистрации/авторизации
2. Зажать ЛКМ в пределах модального окна
3. Увести курсор за пределы
4. Отпустить кнопку мыши

**Фактический результат**: модальное окно закрывается
**Ожидаемый результат**: модальное окно не закроется

**Артефакты**:
* gif
![Peek 2023-03-07 12-50](https://user-images.githubusercontent.com/91963263/223386227-2dc48a11-d140-47f2-86eb-7abf3d4e5346.gif)

**Comment by Ivan-Bir** [comment]
Исправил

**Comment by Andeo1812** [comment]
Апрув

**Comment by Mike5535** [comment]
Аппрув

**Comment by lonkidely** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
аппрув
