### ISSUE TITLE
VDonate. Создание подписки. Не появляется правильное сообщение об ошибке при вводе цены при создании авторской подписки

### ISSUE THREAD

**Issue by themilchenko** [VK-BMSTU-QA/homework-2-spring-2023#51]
`Приоритет:` Low
`URL:` https://vdonate.ml/profile?id=6
`Окружение:` Firefox Version 110.0.1 (64-bit)

#### Как воспроизвести:

1. Авторизироваться;
2. Зайти на свой профиль;
3. Если авторизированный пользователь не автор, нажать на кнопку "Стать автором";
4. Нажать на плюс, находящийся сверху страницы рядом с надписью "Уровни подписок";
5. Вставить заранее скопированный текст, не являющийся числом;
6. Заполнить остальные поля правильными значениями;
7. Нажать на кнопку "Создать".

`Ожидаемый результат`: Вывод ошибки о том, что данный тип символов не является числом, либо не давать вставить текст в это поле.
`Фактический результат`: Текст ошибки не дает точное ее обоснование.

#### Артефакты

![price_error](https://user-images.githubusercontent.com/70635146/224857875-97d27ae9-9282-4b4e-b4e6-37ccf4b90453.png)

**Comment by MrLeonardPak** [comment]
Аппрув

**Comment by zeronethunter** [comment]
Аппрув

**Comment by george007361** [comment]
Аппрув
