### ISSUE TITLE
VDonate. Возврат средств. Не возвращаются деньги отправителю при мгновенном удалении автором подписки

### ISSUE THREAD

**Issue by themilchenko** [VK-BMSTU-QA/homework-2-spring-2023#52]
`Приоритет:` Critical
`URL:` https://vdonate.ml/profile?id=6
`Окружение:` Firefox Version 110.0.1 (64-bit)

#### Как воспроизвести:

1. Авторизироваться;
2. Найти автора admin;
3. На странице автора найти уровень подписки под названием "*" и произвести оплату;
4. Авторизироваться за пользователя admin;
5. Удалить подписку под названием "*";

`Ожидаемый результат`:  Деньги должны вернуться отправителю.
`Фактический результат`: Средства остаются на счету у автора.

**Comment by MrLeonardPak** [comment]
Аппрув

**Comment by zeronethunter** [comment]
Аппрув

**Comment by george007361** [comment]
Аппрув

**Comment by mistergahan** [comment]
Мне ок
