### ISSUE TITLE
BugOverload. Страница пользовательской коллекции. Можно перейти на приватную страницу другого пользователя

### ISSUE THREAD

**Issue by Andeo1812** [VK-BMSTU-QA/homework-2-spring-2023#53]
**Приоритет**: средний
**URL**: https://movie-gate.online/user/collection/2/
**Окружение**: ОС Linux version 6.1.11-arch1-1, Браузер Google chrome, версия 109.0.5414.74 (Официальная сборка) (64 бит), масштаб 100%, разрешение 1920х1080

**Шаги воспроизведения**:

1. Перейти на страницу приватной коллекции другого пользователя https://movie-gate.online/user/collection/2/

**Фактический результат**: Черный экран без уведомлений
**Ожидаемый результат**:  Сообщение "Данная коллекция закрыта" 

**Артефакты**:

- Скриншот

![image](https://user-images.githubusercontent.com/84146116/224553030-5bbeafdb-b8f7-45cc-a503-f5dc96463278.png)

**Comment by lonkidely** [comment]
> Ожидаемый результат: Сообщение "Данная коллекция закрыта" без перехода на страницу

Если ты в первый раз сразу по такому урлу пройдешь, сообщению негде будет отобразиться. Тогда уж можно перейти по странице, но отрисовать сообщение об ошибке.

Аналогично, разметку поправить надо

**Comment by Ivan-Bir** [comment]
Аппрув

**Comment by Andeo1812** [comment]
UPD

**Comment by Ivan-Bir** [comment]
Аппрув

**Comment by Mike5535** [comment]
Аппрув

**Comment by lonkidely** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
Аппрув
