### ISSUE TITLE
BugOverload. Можно поделиться личной приватной коллекцией

### ISSUE THREAD

**Issue by Andeo1812** [VK-BMSTU-QA/homework-2-spring-2023#54]
**Приоритет**: низкий
**URL**: https://movie-gate.online/user/collection/2/
**Окружение**: ОС Linux version 6.1.11-arch1-1, Браузер Google chrome, версия 109.0.5414.74 (Официальная сборка) (64 бит), масштаб 100%, разрешение 1920х1080

**Шаги воспроизведения**:

1. Авторизоваться
2. Перейти на страницу личной приватной коллекции
3. Нажать кнопку в правом углу экрана

**Фактический результат**: Присутствие кнопки поделиться приватной коллекцией.
**Ожидаемый результат**:  Отсутствие кнопки поделиться

**Артефакты**:

- Скриншот

![image](https://user-images.githubusercontent.com/84146116/224553052-1cf15fc9-a776-4e7f-abe1-9f8e3a253b80.png)

**Comment by lonkidely** [comment]
Добавь пожалуйста разметку, жирным ключевые слова выдели (приоритет, url, окружение, шаги, факт/ожид результат, артефакты)
Из названия issue я бы убрал "личную", это вроде не принципиально
> 1. Перейти на страницу приватной - приватной коллекции https://movie-gate.online/user/collection/2/

Дублируется "приватной"
