### ISSUE TITLE
BugOverload. Главная. Уведомления обрезаются при заполнении высоты страницы

### ISSUE THREAD

**Issue by lonkidely** [VK-BMSTU-QA/homework-2-spring-2023#55]
**Приоритет:** низкий
**URL:** https://movie-gate.online/
**Окружение:** ОС Windows 11 (build 22621.1344), Браузер Google Chrome 111.0.5563.65 (Official Build) (64-bit), масштаб 100%, разрешение экрана 1366х768

**Шаги воспроизведения:**
1. Авторизоваться или зарегистрироваться на сайте
2. Подождать 2 минуты, пока появится хотя бы 4 уведомления

**Фактический результат:** Верхнее уведомление не влазит, сайт не умеет корректно обрабатывать такой случай, из-за чего уведомление обрезается
**Ожидаемый результат:** Верхнее уведомление должно исчезнуть с экрана

**Артефакты:**

- Скриншот
![image](https://user-images.githubusercontent.com/30394005/224989711-81db9d78-a4e2-4629-bed4-e8c9e99b35dc.png)

**Comment by Ivan-Bir** [comment]
Аппрув

**Comment by Ivan-Bir** [comment]
Аппрув

**Comment by Andeo1812** [comment]
Аппрув

**Comment by alexey-ershkov** [comment]
аппрув
