### ISSUE TITLE
BugOverload. На небольших экранах текст с ошибкой в формах  слишком мал

### ISSUE THREAD

**Issue by Mike5535** [VK-BMSTU-QA/homework-2-spring-2023#60]
Приоритет: низкий
URL: https://movie-gate.online/profile/
Окружение: 
1. ОС Windows 10 19045.2604, Браузер Google chrome, версия 111.0.5563.64 (Официальная сборка) (64 бит), масштаб 100%, разрешение 320x480, 141 dpi
2. OC Android 8.1.0, Браузер Opera 72.5.3767.69342, масштаб 100%, разрешение  2160x1080, 403 dpi

Шаги воспроизведения:

    1. Перейти на страницу профиля
    2. Нажать на карандаш для редактирования профиля
    3. Ввести в появившемся поле один любой символ
   
Фактический результат: Текст с ошибкой появляется, но при этом его трудно прочесть. Размер шрифта 7px
Ожидаемый результат: Текст с ошибкой появляется под неправильно заполненным инпутом, при этом сам текст легко прочесть. Размер шрифта должен быть не менее 12px

Артефакты:
png - Windows
![image](https://user-images.githubusercontent.com/84146116/224552125-aaffea29-7a1b-4c81-a67c-2137979c3f98.png)
png - Android
![photo_2023-03-16_16-11-06](https://user-images.githubusercontent.com/84146116/225629606-b1aae0e3-0855-4591-aee3-409c26357a38.jpg)

**Comment by Ivan-Bir** [comment]
Можем назвать конкретные размеры шрифтов, потому что если мы закладывали маленький текст, то не _баг_?

**Comment by lonkidely** [comment]
аппрув

**Comment by Andeo1812** [comment]
Апрув
